### ISSUE TITLE
[Bug] Invalid requirement specification: u'_loader'

### ISSUE THREAD

**Issue by bruce30262** [Jinmo/idapkg#9]
### Env
* IDA version 7.2
* Windows 10 64 bit
* idapkg version 0.1.1

### Detail
I've uploaded a loader for IDA Pro: https://idapkg.com/p/mclf_loader  
In case you want the zip file: [mclf_loader.zip](https://github.com/Jinmo/idapkg/files/3235262/mclf_loader.zip)  

When I copy the command in the web page and execute it, I got the following error messages:  

```
Python>pkg.install('mclf_loader', repo='https://api.idapkg.com')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\commands.py", line 41, in install
    spec = _parse_spec(spec)
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\commands.py", line 21, in _parse_spec
    semantic_version.Spec(version)
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\semantic_version\base.py", line 505, in __init__
    subspecs = [self.parse(spec) for spec in specs_strings]
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\semantic_version\base.py", line 511, in parse
    return tuple(SpecItem(spec_text) for spec_text in spec_texts)
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\semantic_version\base.py", line 511, in <genexpr>
    return tuple(SpecItem(spec_text) for spec_text in spec_texts)
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\semantic_version\base.py", line 425, in __init__
    kind, spec = self.parse(requirement_string)
  File "C:\Users\<omit>\idapkg\packages\idapkg\pkg\semantic_version\base.py", line 440, in parse
    raise ValueError("Invalid requirement specification: %r" % requirement_string)
ValueError: Invalid requirement specification: u'_loader'
```

BTW if I place the **mclf_loader** dir under the **idapkg/packages** folder, it works perfectly fine.

**Comment by Jinmo** [comment]
Fixed in 1ab4522, thanks! It was an issue of mismatch between [package schema](https://github.com/Jinmo/idapkg-api/blob/master/src/package-schema.ts) and [`pkg.install`](https://github.com/Jinmo/idapkg/blob/f38d5e9354e3d9f4828d0b03c06a6bd1ac79b403/pkg/commands.py#L15).
